### ISSUE TITLE
Bugs Auto Cutter

### ISSUE THREAD

**Issue by DOOMachevsky** [TeamDmfMM/Extra-Food#10]
With the auto cutter can be multiplied by any object. Napimer by putting diamonds and using the shift key to move into the inventory, they will double. Same with any other object. I am from Russia so sorry for the rough translation. Thank you for the modification of class!

**Comment by dmf444** [comment]
Can you please tell me the version of Extra Food you're using? I think I fixed it a while ago

**Comment by DOOMachevsky** [comment]
версия ExtraFood-1.7.10-0.7.12. Скачал с сайта http://www.curse.com/mc-mods/minecraft/222348-extra-food#t1:other-downloads

**Comment by DOOMachevsky** [comment]
as it was in all previous versions

**Comment by DOOMachevsky** [comment]
Version ExtraFood-1.7.10-0.7.12. Download http://www.curse.com/mc-mods/minecraft/222348-extra-food#t1:other-downloads

**Comment by DOOMachevsky** [comment]
as it was in all previous versions

**Comment by DOOMachevsky** [comment]
link to a video where I demonstrate this bug https://youtu.be/7Ih8_T4idEg

**Comment by dmf444** [comment]
Thanks for that. Will look into it tonight and see what I can do

**Comment by dmf444** [comment]
Fixed in next version, Thanks for reporting!

**Comment by DOOMachevsky** [comment]
Thank you very much, everything is working properly! Very cool modes!I do not install just because it was a bug. This is the best mode for food.
