### ISSUE TITLE
Sound Problems in Juice Blender

### ISSUE THREAD

**Issue by dmf444** [TeamDmfMM/Extra-Food#11]
``````````````````````````
Confirming this crash. Also adding that when you craft/place the juicer and turn it on the sound caused an area of effect client crash. Had to force client update to repair. And multiple people had this issue. Had to us long range explosives to remove juice blender to stop its effect. lol. If this mod is still being updated would appreciate an update (Just a, "Ya, we are still here." would do) to this thread so I know If i need to remove the mod from client/server packs.
```````````````````````````
`````````````````
Not sure as far as mine go. I'll grab my error log from when it happened if I can find it, And the sound thing was what popped up in console. Plus made sence to me as far as an aoe client crash .
 I'll report back when I find out more. Here is the client/server setup if it helps.
 Server modpack: https://www.dropbox.com/s/r7epwjv32kes7rw/TAEserver.zip?dl=0
 Client modpack: https://www.dropbox.com/s/bjzua4ot9x7efa7/TechnAintEasy.zip?dl=0
````````````````
Originally reported in #9 by @skittishtrigger

**Comment by Badcholo** [comment]
I can confirm a Crash, but mine is after i place it down. I place bananas inside it and after the bar reaches the right side the game crashes. I have no crash report but i am using the latest forge.
I will try removing other mods to see if they may be causing something. i made a quick video.
https://www.dropbox.com/s/a0vkvklwbsiee40/javaw%202015-05-13%2021-12-51-888.avi?dl=0

**Comment by dmf444** [comment]
Can you post the crash log?

**Comment by Badcholo** [comment]
I was in single player and it didn't crash. The game just closed and it went to the title screen.

**Comment by dmf444** [comment]
Can you post the log from the client? It should be in the .minecraft folder inside the logs folder. Specifically the client_latest.log

**Comment by Badcholo** [comment]
https://www.dropbox.com/sh/ss8w4ny1jfch3hl/AAAaBwCTXZyUkw93TvZgh2wLa?dl=0

**Comment by Badcholo** [comment]
was it something i needed to update?

**Comment by dmf444** [comment]
You were using the latest version of forge. There were several changes to the way fluids work, which I had not changed. The newest version of Extra Food shouldn't crash anymore, everything was reimplemented.

**Comment by Badcholo** [comment]
awsome!! Thank you so much, I really like being able to make smoothies.
