### ISSUE TITLE
Feature Request: Hunger Potion

### ISSUE THREAD

**Issue by Badcholo** [TeamDmfMM/Extra-Food#15]
I would like to suggest a Potion that removes 2 hunger bars instantly at a time. It can be crafted using rotten flesh and optional cooked in a furnace. Simple as that. Water bottle combined with rotten flesh to make a Hunger Potion.

**Comment by mincrmatt12** [comment]
Just a quick notice, we are making a mod to enhance minecraft hunger (not released yet), and this would probably belong there.

**Comment by Badcholo** [comment]
Oh well i'm excited to see it. I currently use Hunger Overhaul and Spice of Life to alter hunger, plant growth and saturation.

**Comment by dmf444** [comment]
Our new mod will allow the change in hunger and saturation at release. Plants are planned but not at release

**Comment by Badcholo** [comment]
Any idea on a release for the hunger mod?

**Comment by dmf444** [comment]
Finishing up an In game guide for it, I'm thinking a meta (without the guide) should be out by end of month.

**Comment by Badcholo** [comment]
Awesome! No rush, i've just been looking forward to it. I'll test it out for you when you release it. I'm really great at finding bugs and compatibility with other mods.

**Comment by mincrmatt12** [comment]
fun fact: I'm supposed to be writing that code. And I haven't been! (Well, I did a bunch of it yesterday, so expect it in about 4-5 days)

**Comment by dmf444** [comment]
Hello Badcholo. Sorry for the wait, but our new mod is out for beta testing. To download it, see https://drone.io/github.com/TeamDmfMM/StarvationAhoy/files . It will eventually be put on curseforge. Also, the potion is called Badcholo's Brew, in your honor. Thanks for the idea!

**Comment by Badcholo** [comment]
Your so Awesome, Mod Showcase as soon as you give the say!
latest video, https://www.youtube.com/watch?v=ZPpi0PKEkRQ
youtube channel
https://www.youtube.com/channel/UCVRDbrSypbA696FHcaiBhkg

**Comment by Badcholo** [comment]
Where should i post the uhmm crash reports
http://pastebin.com/bRNFTwzx

placed 2 spit roast stands, 2 blocks apart and placed a stick on it, it created the roater thingy just fine.
I then right clicked the handle without any dead animal on yet and i crashed.

**Comment by Badcholo** [comment]
I can't believe your making this mod!!! I'm so freaking excited for it!!
I had a mod like this on 1.6.4, oh my god i miss it so much!
So Epic!!, I'm so glad your still working on it.

**Comment by dmf444** [comment]
Thanks! I saw it and we spun it off into its own mod. Bug reports go here: https://github.com/TeamDmfMM/StarvationAhoy/issues however I've already moved the one you just made there. If you want to review it, go ahead, however there are a few things that I'll have to tell you to showcase.

**Comment by Badcholo** [comment]
Feature Suggestion: Saturation overlay without wearing armor. maybe you have plans for it but unless it's top tier armor, players won't wear it unless they need to quickly see their saturation bar.

I freaking love the config to change hunger values, Amazing! i've needed this so badly for so long.

**Comment by Badcholo** [comment]
Sure thing let me know anything you'd like to add to the showcase. Shout outs, future plans, anything really.
