### ISSUE TITLE
Muffins saturation

### ISSUE THREAD

**Issue by Badcholo** [TeamDmfMM/Extra-Food#16]
Eating Muffins seems to give full saturation up to the amount of your hunger filled, With 3 hunger bar i ate a muffin and my saturation was filled all the way up to the amount of hunger filled. Is this intentional?

**Comment by mincrmatt12** [comment]
Just to clarify, do you mean that the hunger and saturation is the same for all muffins?

**Comment by Badcholo** [comment]
no, My modpack is Mojangsters from the technic launcher. We have a Saturation overlay bar that shows how much saturation you get from foods. It seems that steak and other foods gives about half saturation as hunger amount. So 4 hunger bars filled = 2 Saturation overlay bars filled. With your muffins I get like 3 hunger bars filled = up to 10 of saturation. Saturation is filled up to the amount of hunger filled by your muffins. I don't know how to make the muffins either. I use Hunger Overhaul mod and Spice of life mod.

**Comment by Badcholo** [comment]
i'll make a vid.

**Comment by mincrmatt12** [comment]
Ok, I get your point, but that may be intentional. I guess dmf444 has to look at this as he did the muffin, so he will know, but I will look into it for you when I have time

**Comment by mincrmatt12** [comment]
this has been open for too long, and it appears to be solved, so closing
