### ISSUE TITLE
Tomatoes plants drop tomatoes whether mature or not.

### ISSUE THREAD

**Issue by MoxieGrrl** [TeamDmfMM/Extra-Food#18]
Each tomato crafted in a crafting grid gives two seeds. If you plant those seeds and immediately harvest them you get a tomato back whether they are mature or not. This allows you to continually dupe tomatoes.

Either have tomatoes only give one seed each or make the non-mature plants drop seeds instead of tomatoes.

**Comment by dmf444** [comment]
This is the 1.7 version? (Just making sure so I push up to 1.8)

**Comment by DEX47** [comment]
I am getting these results from ExtraFood-1.7.10-0.7.25.

**Comment by mincrmatt12** [comment]
has he (@dmf444) really not fixed it yet? god, i'll go pester him in the next three-four days

**Comment by AKTheKnight** [comment]
Still getting this in 1.8.9-0.7.51
