### ISSUE TITLE
worldgen issues

### ISSUE THREAD

**Issue by kreezxil** [TeamDmfMM/Extra-Food#22]
Your items tree items are causing some issues in the console and appear to be fighting with Thaumcraft on new world generation.

https://gist.github.com/0f87c564aac793d995b0

**Comment by dmf444** [comment]
Although highly probable, I'm not sure how to debug this seeing as TC is closed source. I'll see if I can clean up my generation code, however, the server log doesn't help in this scenario. Is it possible for you to try without TC but with Extra Food?

**Comment by kreezxil** [comment]
You'll have to open a ticket with them.

**Comment by dmf444** [comment]
This bug may still exist, but due to 1.8.9/1.9/1.9.4/1.10/1.10.2 being out and the fact that it could not be replicated, i'm going to close it.
