### ISSUE TITLE
Olives?

### ISSUE THREAD

**Issue by shufunk** [TeamDmfMM/Extra-Food#23]
So apparently I got an olive from a banana tree and the olive had no texture and would crash the game when i tried to look up a recipe in NEI

**Comment by mincrmatt12** [comment]
Oh. Actually you found an olive tree (still in beta) that right now look the same as banana trees. I assume you are on the beta branch?

**Comment by dmf444** [comment]
Thanks for the report. Will push out a release later today.

**Comment by shufunk** [comment]
The banana tree initially had 3 things of banana's which i took down 1st. Cut the tree down and the leaves decayed like they normally do but got an olive somehow. I didn't see if it said olive leaf or not but will make a video if i encounter another one.

**Comment by shufunk** [comment]
Here is a video of the bug happening. Just to clarify I found this mod today so whatever version it was on the curse launcher at the time i originally posted this bug report is the version i have which i think is 0.7.45 https://www.youtube.com/watch?v=R-bPYEG2-jE

Before i submit this follow up i noticed that 0.7.49 was just released so if that was the patch for bug i will download that version and do another test

**Comment by dmf444** [comment]
The gen thing is defiantly a bug. That's an olive tree spawning underneath a banana tree. Will fix this week. Newest version will contain the olive texture

**Comment by shufunk** [comment]
Yeh loving the olive tree by itself. a great resource of food i take before i go on a cave run. Now if only we can make cocktails

**Comment by mincrmatt12** [comment]
Oh. Should be in juice blender soon if dmf444 approves
