### ISSUE TITLE
Crashes with Biomes O Plenty

### ISSUE THREAD

**Issue by BBoldt** [TeamDmfMM/Extra-Food#26]
https://github.com/Glitchfiend/BiomesOPlenty/issues/611

**Comment by mincrmatt12** [comment]
Just read that issue, looking in to it.

**Comment by DoughnutDev** [comment]
Having this same issue on 3.0.0.1743 of Biomes O Plenty and I am using ExtraFoods 0.7.51.

**Comment by dmf444** [comment]
Unable to reproduce. If possible, can I have a world download?

**Comment by Morpheus1101** [comment]
Has the release that fixes this issue been released yet?  If it has then im still getting an error.

http://pastebin.com/Vd8ZF3Vy

**Comment by dmf444** [comment]
I thought I had fixed this... Looks like I have to check again

**Comment by Morpheus1101** [comment]
It does get annoying when that happens

**Comment by mincrmatt12** [comment]
So after reading the crash log again, and then reading the bit that it's crashing on, I have come to a very clear conclusion: this was never fixed. Luckily, I figured out how to fix it and this should be fixed in the next commit

**Comment by mincrmatt12** [comment]
darn it didn't work...

**Comment by mincrmatt12** [comment]
And now its fixed. Not closing until released, though
