### ISSUE TITLE
Sushi and Pasta with meatballs sprites reversed

### ISSUE THREAD

**Issue by thephoenixlodge** [TeamDmfMM/Extra-Food#31]
As per the title, sushi currently has the Pasta with meatballs texture and vice versa.

**Comment by dmf444** [comment]
What version, 1.7.10 or 1.8.9?

**Comment by thephoenixlodge** [comment]
1.8.9

**Comment by dmf444** [comment]
Can I see a photo of this? Kinda curious as to what you are seeing that's showing the two with mixed images

**Comment by mincrmatt12** [comment]
fixed in next release

**Comment by mincrmatt12** [comment]
no longer fixed because fix breaks some other peoples cpus
