### ISSUE TITLE
Crash when trying to use hopper to send items into the oven

### ISSUE THREAD

**Issue by GWYOG** [TeamDmfMM/Extra-Food#36]
I'm not quite understand what does these following sentences mean in the cookbook, so I use a hopper to test. However, MC crashes when I tried to send items (like cheese slices) into the oven by hoppers through the top/side face of the oven.

**"The oven is only partially automatible. Only food in the output slot can be pulled out by hoppers and only from the bottom of the oven. This is partially due to the residual heat buildup inside the oven."**
What does the word "partially" really mean? How will the heat stops automating? I've made 32 pizza with cheese and olive but it seems that nothing stops the hopper's pulling out.

Here is the crashreport: http://pastebin.com/Pj18JFP9

**Comment by dmf444** [comment]
Partially mean "in part" or "not completely". Basically, you should only be able to use hoppers to remove items from the oven, not put anything in.

**Comment by GWYOG** [comment]
But why would Minecraft crash when I attempted to put anything in? This crash is so severe that I can't get into this world again unless I remove the hopper in some ways. This seems to be a bug.

**Comment by dmf444** [comment]
I believe this is due to a change in forge. I'll look into it

**Comment by mincrmatt12** [comment]
dmf444 was wrong, he just made a derp. Fixed in next release
