### ISSUE TITLE
Cheese press and automation with pipes (BC or NeoTech)

### ISSUE THREAD

**Issue by BrewAndCode** [TeamDmfMM/Extra-Food#38]
When you pipe in buckets of milk the cheese press will accept those buckets of milk in not only the 3 source blocks of the GUI but also the results block halting the cheese-making process.

Also; any additional buckets of milk that are piped into the block while in the state are destroyed(lost)

please make it so that source items (milk) can only be placed in the appropriate spots :)

**Comment by mincrmatt12** [comment]
Should be fixed in this push, but I still need to test

**Comment by mincrmatt12** [comment]
Fixed
