### ISSUE TITLE
Bucket Crash in 1.9

### ISSUE THREAD

**Issue by dmf444** [TeamDmfMM/Extra-Food#41]
> I have encountered a crash between tinker's construct and Extra food in 1.9.  Here is the crash report: http://paste.ee/p/lP0aE.
> It's connected to the bucket. It happened when I was trying to add water through the drain in the smeltery, by way of a water bucket and right clickin the drain. In that instance it crashed. Here is a short exceprt from thr crash report. I hope you can make some sense out of this!
> `java.lang.ClassCastException: net.minecraft.block.BlockStaticLiquid cannot be cast to dmf444.ExtraFood.Common.fluids.GeneralFluid
> at dmf444.ExtraFood.Common.items.BucketEdible.drain(BucketEdible.java:136)
> at net.minecraftforge.fluids.FluidUtil.tryEmptyFluidContainerItem(FluidUtil.java:369)
> at net.minecraftforge.fluids.FluidUtil.tryEmptyFluidContainerItem(FluidUtil.java:225)
> at slimeknights.tconstruct.smeltery.block.BlockSmelteryIO.func_180639_a(BlockSmelteryIO.java:97)
> `
> and so on............
> I hope this can be fixed. I wasn't sure who to contact, you or the author if TC. But since it looks like your mod was the main issue, I decided to contact you :)
> Thanks! 

Taken from Curse.

**Comment by xhaavardx** [comment]
Which Forge version did you compile with? There has been a fix to what seems to be going on here. 
It came in version 1930, and is merged into version 1937. 

Here is the the mentioned fix, taken from the changelog. [http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.9.4-12.17.0.1937/forge-1.9.4-12.17.0.1937-changelog.txt](url)
> Fixed FluidUtil.tryEmptyFluidContainerItem not checking if the tank can accept fluids first. Closes #2527

Might this be the culprit?

**Comment by dmf444** [comment]
I doubt it. The error is due to some casting that I have incorrectly done

**Comment by mincrmatt12** [comment]
It's because of how we implemented the salty water stuff, so its trying to find our liquids inside minecraft's water block
