### ISSUE TITLE
Orange Tree Crash?

### ISSUE THREAD

**Issue by AnimeWalker** [TeamDmfMM/Extra-Food#43]
I have had multiple crashes happen due to the orange trees in 1.9.4. Here is the report: http://paste.ee/p/qhMZ5
Whenever I get close to an orange tree, the game crashes. It doesn't crash when I get near orange tree saplings. I have multiple mods installed that I play with, but this is the only crash I have encountered when playing with them all together. Thank you for taking your time to make this mod, its really fun!

**Comment by dmf444** [comment]
Although I don't doubt the crash you're talking about, the log provides no reason for a crash. If possible, could you make a video or give me a list of the mods you are playing with?

**Comment by AnimeWalker** [comment]
Here is the list of the mods I am playing with: 

-A backpack mod by Brad16840 
http://mod-minecraft.net/backpacks-mod-brad16840/

-The Blood Magic mod
http://minecraft.curseforge.com/projects/blood-magic

-An Emerald and Obsidian mod for tool, weapons and armor
http://mods.curse.com/mc-mods/minecraft/228314-emerald-obsidian-mod#t1:other-downloads

-Iron Chest mod 
http://minecraftsix.com/iron-chests-mod/

-Just Enough Items Mod
http://www.minecraftyard.com/just-enough-items-mod/

-Lucky Block Mod
http://www.minecraftascending.com/projects/lucky_block/lucky_block.html

-Mantle 
http://minecraft.curseforge.com/projects/mantle

-Tinkers Construct
http://minecraft.curseforge.com/projects/tinkers-construct

Those are all the mods I used when playing with Extra Food, and if you would like me to make a video I can :3

**Comment by dmf444** [comment]
I'm testing it on my PC, however it would be great to have a video. Thanks!

**Comment by dmf444** [comment]
Wait a minute: 
Looks like i found the source of the crash! Don't look at the oranges, and you'll be fine!
Great way to play, ya? No? You want to get oranges? Fine I'll fix it (and have a conversation with myself as well)

**Comment by AnimeWalker** [comment]
Thank you!
