### ISSUE TITLE
Cookbook is empty

### ISSUE THREAD

**Issue by CA2020** [TeamDmfMM/Extra-Food#7]
Version ExtraFood-1.7.10-0.7.5

The Cookbook is empty, it shows like an "Achievement tree" but no matter which one you click, the pages are empty.

Also the names for all the items on the mod are missing, they just showing as "item.Cookbook.name"

Hope this can be fixed as I would like to try this mod more.

Thanks a lot.

**Comment by dmf444** [comment]
This should be fixed in the newest version of Extra Food. (0.7.10 I think). If it's not, just let me know.

**Comment by CA2020** [comment]
Yes, fixed in version 0.7.10

Thanks a lot ;)
