### ISSUE TITLE
Eating the new muffin causes a crash.

### ISSUE THREAD

**Issue by Badcholo** [TeamDmfMM/Extra-Food#9]
Servercrash
http://pastebin.com/7Q7afqnc
clientcrash
http://pastebin.com/yLyKYaK9

I was playing in SSP and just ate the muffin, crashed instantly.
newest forge

**Comment by skittishtrigger** [comment]
Confirming this crash. Also adding that when you craft/place the juicer and turn it on the sound caused an area of effect client crash. Had to force client update to repair. And multiple people had this issue. Had to us long range explosives to remove juice blender to stop its effect. lol. If this mod is still being updated would appreciate an update (Just a, "Ya, we are still here." would do) to this thread so I know If i need to remove the mod from client/server packs.

**Comment by dmf444** [comment]
I'm not dead! It is still being updated but there cannot possibly be a sound error, I've never added any sounds to my machines. Crash log please?

**Comment by dmf444** [comment]
Also, does this bug happen with pizza as well?

**Comment by skittishtrigger** [comment]
Not sure as far as mine go. I'll grab my error log from when it happened if I can find it, And the sound thing was what popped up in console. Plus made sence to me as far as an aoe client crash .
I'll report back when I find out more. Here is the client/server setup if it helps.
Server modpack: https://www.dropbox.com/s/r7epwjv32kes7rw/TAEserver.zip?dl=0
Client modpack: https://www.dropbox.com/s/bjzua4ot9x7efa7/TechnAintEasy.zip?dl=0

**Comment by Badcholo** [comment]
hey skittishtrigger..
What long range explosives are you using? What mod is that from?

**Comment by dmf444** [comment]
this bug will be fixed as of new version of mod (should be above 0.7.12) Thanks for reporting

@skittishtrigger I'm going to open a new issue for your problem, continue it there please. 
:+1:
